#running shell script with github workflow
name: Check for push
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run migration script
        #run: bash /migrate-repositories-to-github.sh
        run: bash migrate-repositories-to-github.sh ado_repositories.csv
        
      ##- run: |
        ##  ./list-ADOonprem-repositories.sh

          

       # run:  bash list-ADOonprem-repositories.sh > ado_repositories.csv
             ## bash migrate_repo.sh ado_repositories.csv
        
      ##- name: printing the list
      ##  run: |
        ##  echo Here is the list
        ##  ls -a
         ## pwd
        
        
        ##shell: bash
