#running bash script with github workflow
name: Check for push
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run migration script
        #run: bash /migrate-repositories-to-github.sh
        #shell: bash
        #run:  ./migrate-repositories-to-github.sh ado_repositories.csv
        #run: ./migrate_repo.sh ado_repositories.csv
        run: |
          bash migrate_repo.sh ado_repositories.csv
